//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FPT_Final.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Link
    {
        public long id { get; set; }
        public long TrainerID { get; set; }
        public long TraineeID { get; set; }
        public long CourseID { get; set; }
    
        public virtual Course Course { get; set; }
        public virtual Trainee Trainee { get; set; }
        public virtual Trainer Trainer { get; set; }
    }
}
