//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FPT_Final.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Trainee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Trainee()
        {
            this.Links = new HashSet<Link>();
        }
    
        public long TraineeID { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public string TraineeCode { get; set; }
        public string Name { get; set; }
        public int Age { get; set; }
        public int Phone_number { get; set; }
        public string Programming_language { get; set; }
        public Nullable<long> positionId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Link> Links { get; set; }
        public virtual position position { get; set; }
    }
}
